/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ControlCitas;
import interfaces.Observer;
import java.awt.CardLayout;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import modelo.Cita;
import modelo.Medico;

/**
 *
 * @author renee
 */
public class PantallaCitas extends javax.swing.JFrame implements Observer {

    private ControlCitas controlador;

    /**
     * Creates new form PantallaCitas
     */
    public PantallaCitas(ControlCitas controlador) {
        initComponents();
        this.controlador = controlador;
        this.controlador.agregarObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombrePaciente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNSSPaciente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDoctores = new javax.swing.JList<>();
        jPanelInfo = new javax.swing.JPanel();
        panelDetallesMedico = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblEspecialidad = new javax.swing.JLabel();
        lblConsultorio = new javax.swing.JLabel();
        comboDias = new javax.swing.JComboBox<>();
        comboHoras = new javax.swing.JComboBox<>();
        panelTicketCita = new javax.swing.JPanel();
        lblTicketPaciente = new javax.swing.JLabel();
        lblTicketMedico = new javax.swing.JLabel();
        lblTicketConsultorio = new javax.swing.JLabel();
        lblTicketFechaHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Paciente:");

        lblNombrePaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombrePaciente.setText("nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("NSS:");

        lblNSSPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNSSPaciente.setText("nombre");

        listaDoctores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaDoctoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaDoctores);

        jPanelInfo.setLayout(new java.awt.CardLayout());

        jButton1.setText("Apartar Cita");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblEspecialidad.setText("jLabel3");

        lblConsultorio.setText("jLabel4");

        comboDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiasActionPerformed(evt);
            }
        });

        comboHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelDetallesMedicoLayout = new javax.swing.GroupLayout(panelDetallesMedico);
        panelDetallesMedico.setLayout(panelDetallesMedicoLayout);
        panelDetallesMedicoLayout.setHorizontalGroup(
            panelDetallesMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesMedicoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(panelDetallesMedicoLayout.createSequentialGroup()
                        .addGroup(panelDetallesMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspecialidad)
                            .addComponent(lblConsultorio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelDetallesMedicoLayout.createSequentialGroup()
                .addComponent(comboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
        );
        panelDetallesMedicoLayout.setVerticalGroup(
            panelDetallesMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEspecialidad)
                .addGap(18, 18, 18)
                .addComponent(lblConsultorio)
                .addGap(18, 18, 18)
                .addGroup(panelDetallesMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanelInfo.add(panelDetallesMedico, "card2");

        lblTicketPaciente.setText("jLabel3");

        lblTicketMedico.setText("jLabel4");

        lblTicketConsultorio.setText("5");

        lblTicketFechaHora.setText("jLabel6");

        javax.swing.GroupLayout panelTicketCitaLayout = new javax.swing.GroupLayout(panelTicketCita);
        panelTicketCita.setLayout(panelTicketCitaLayout);
        panelTicketCitaLayout.setHorizontalGroup(
            panelTicketCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTicketCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTicketPaciente)
                    .addComponent(lblTicketMedico)
                    .addComponent(lblTicketConsultorio))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(panelTicketCitaLayout.createSequentialGroup()
                .addComponent(lblTicketFechaHora)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelTicketCitaLayout.setVerticalGroup(
            panelTicketCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTicketPaciente)
                .addGap(18, 18, 18)
                .addComponent(lblTicketMedico)
                .addGap(18, 18, 18)
                .addComponent(lblTicketConsultorio)
                .addGap(18, 18, 18)
                .addComponent(lblTicketFechaHora)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelInfo.add(panelTicketCita, "panelTicketCita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombrePaciente))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNSSPaciente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombrePaciente)
                    .addComponent(jLabel2)
                    .addComponent(lblNSSPaciente))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDoctoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaDoctoresValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            int indice = listaDoctores.getSelectedIndex();
            if (indice != -1) {
                
                controlador.seleccionarMedico(indice);
            }
        }
    }//GEN-LAST:event_listaDoctoresValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (comboDias.getSelectedItem() != null && comboHoras.getSelectedItem() != null) {

            String diaSeleccionado = comboDias.getSelectedItem().toString();
            String horaSeleccionada = comboHoras.getSelectedItem().toString();

            controlador.agendarCita(diaSeleccionado, horaSeleccionada);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor. seleccione un día y una hora disponibles.", "Datos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiasActionPerformed
        // TODO add your handling code here:
        
        if (comboDias.getSelectedItem() == null) {
            return;
        }
        Medico medicoSel = controlador.getMedicoSeleccionado();
        String diaSeleccionado = comboDias.getSelectedItem().toString();
        
        comboHoras.removeAllItems();

        if (medicoSel != null && medicoSel.getDisponibilidad() != null) {
            List<String> horasDisponibles = medicoSel.getDisponibilidad().get(diaSeleccionado);

            if (horasDisponibles != null) {
                for (String hora : horasDisponibles) {
                    comboHoras.addItem(hora);
                }
            }
        }
    }//GEN-LAST:event_comboDiasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDias;
    private javax.swing.JComboBox<String> comboHoras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultorio;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblNSSPaciente;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblTicketConsultorio;
    private javax.swing.JLabel lblTicketFechaHora;
    private javax.swing.JLabel lblTicketMedico;
    private javax.swing.JLabel lblTicketPaciente;
    private javax.swing.JList<String> listaDoctores;
    private javax.swing.JPanel panelDetallesMedico;
    private javax.swing.JPanel panelTicketCita;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {

        // 1bValidar que haya un paciente (si no hay, no hacemos nada)
        if (controlador.getPacienteActual() == null) {
            return;
        }

        // 2 Actualizamos los datos básicos del paciente en la pantalla
        lblNombrePaciente.setText(controlador.getPacienteActual().getNombre());
        lblNSSPaciente.setText(controlador.getPacienteActual().getNss());

        // 3 llenar lista de doctores si está vacía.
        if (listaDoctores.getModel().getSize() == 0) {
            DefaultListModel<String> modeloLista = new DefaultListModel<>();
            List<Medico> listaMedicos = controlador.getMedicos();
            for (Medico medico : listaMedicos) {
                modeloLista.addElement(medico.getNombre());
            }
            listaDoctores.setModel(modeloLista);
        }

        this.setVisible(true);

        // 4 estado actual del modelo
        Medico medicoSel = controlador.getMedicoSeleccionado();
        Cita citaReciente = controlador.getCitaReciente();
        CardLayout layout = (CardLayout) jPanelInfo.getLayout();

       
        if (citaReciente != null) {
            System.out.println("panel de TICKET");

            lblTicketPaciente.setText(citaReciente.getPaciente().getNombre() + " " + citaReciente.getPaciente().getNss());
            lblTicketMedico.setText(citaReciente.getMedico().getNombre());

            if (citaReciente.getMedico().getConsultorio() != null) {
                lblTicketConsultorio.setText(citaReciente.getMedico().getConsultorio().getNombreConsultorio());
            }

            lblTicketFechaHora.setText(citaReciente.getFecha() + " a las " + citaReciente.getHora());
            layout.show(jPanelInfo, "panelTicketCita");

        } else if (medicoSel != null) {
            
            System.out.println("panel de Detalles del Medico");

            lblEspecialidad.setText("Especialidad " + medicoSel.getEspecialidad());

            if (medicoSel.getConsultorio() != null) {
                lblConsultorio.setText("Consultorio " + medicoSel.getConsultorio().getNombreConsultorio());
            }

            // Limpia y llena los combos
            comboDias.removeAllItems();
            comboHoras.removeAllItems();

            if (medicoSel.getDisponibilidad() != null) {
                for (String dia : medicoSel.getDisponibilidad().keySet()) {
                    comboDias.addItem(dia);
                }
            }
            layout.show(jPanelInfo, "panelDetallesMedico");
        }
    }

}
